# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/qa_work/.jumbo/bin/cmake

# The command to remove a file.
RM = /home/qa_work/.jumbo/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build

# Utility rule file for extern_mklml.

# Include the progress variables for this target.
include CMakeFiles/extern_mklml.dir/progress.make

CMakeFiles/extern_mklml: CMakeFiles/extern_mklml-complete

CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-install
CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-mkdir
CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-download
CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-update
CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-patch
CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-configure
CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-build
CMakeFiles/extern_mklml-complete: third-party/mklml/src/extern_mklml-stamp/extern_mklml-install
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "Completed 'extern_mklml'"
	/home/qa_work/.jumbo/bin/cmake -E make_directory /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles
	/home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles/extern_mklml-complete
	/home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-done

third-party/mklml/src/extern_mklml-stamp/extern_mklml-install: third-party/mklml/src/extern_mklml-stamp/extern_mklml-build
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "Performing install step for 'extern_mklml'"
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-build && $(MAKE) install
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-build && /home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-install

third-party/mklml/src/extern_mklml-stamp/extern_mklml-mkdir:
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "Creating directories for 'extern_mklml'"
	/home/qa_work/.jumbo/bin/cmake -E make_directory /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml
	/home/qa_work/.jumbo/bin/cmake -E make_directory /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-build
	/home/qa_work/.jumbo/bin/cmake -E make_directory /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml
	/home/qa_work/.jumbo/bin/cmake -E make_directory /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/tmp
	/home/qa_work/.jumbo/bin/cmake -E make_directory /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp
	/home/qa_work/.jumbo/bin/cmake -E make_directory /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml
	/home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-mkdir

third-party/mklml/src/extern_mklml-stamp/extern_mklml-download: third-party/mklml/src/extern_mklml-stamp/extern_mklml-mkdir
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "Performing download step for 'extern_mklml'"
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml && wget --no-check-certificate http://10.92.103.11:8080/mklml_lnx_2018.0.3.20180406.tgz -c -O mklml_lnx_2018.0.3.20180406.tgz && tar -zxf mklml_lnx_2018.0.3.20180406.tgz -C /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml && /home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-download

third-party/mklml/src/extern_mklml-stamp/extern_mklml-update: third-party/mklml/src/extern_mklml-stamp/extern_mklml-download
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "No update step for 'extern_mklml'"
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml && /home/qa_work/.jumbo/bin/cmake -E echo_append
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml && /home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-update

third-party/mklml/src/extern_mklml-stamp/extern_mklml-patch: third-party/mklml/src/extern_mklml-stamp/extern_mklml-download
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_6)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "No patch step for 'extern_mklml'"
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml && /home/qa_work/.jumbo/bin/cmake -E echo_append
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml && /home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-patch

third-party/mklml/src/extern_mklml-stamp/extern_mklml-configure: third-party/mklml/tmp/extern_mklml-cfgcmd.txt
third-party/mklml/src/extern_mklml-stamp/extern_mklml-configure: third-party/mklml/src/extern_mklml-stamp/extern_mklml-update
third-party/mklml/src/extern_mklml-stamp/extern_mklml-configure: third-party/mklml/src/extern_mklml-stamp/extern_mklml-patch
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_7)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "Performing configure step for 'extern_mklml'"
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-build && /home/qa_work/.jumbo/bin/cmake -DCMAKE_INSTALL_PREFIX=/home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/third-party/mklml "-GUnix Makefiles" /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-build && /home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-configure

third-party/mklml/src/extern_mklml-stamp/extern_mklml-build: third-party/mklml/src/extern_mklml-stamp/extern_mklml-configure
	$(CMAKE_COMMAND) -E cmake_progress_report /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles $(CMAKE_PROGRESS_8)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold "Performing build step for 'extern_mklml'"
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-build && $(MAKE)
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-build && /home/qa_work/.jumbo/bin/cmake -E touch /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/third-party/mklml/src/extern_mklml-stamp/extern_mklml-build

extern_mklml: CMakeFiles/extern_mklml
extern_mklml: CMakeFiles/extern_mklml-complete
extern_mklml: third-party/mklml/src/extern_mklml-stamp/extern_mklml-install
extern_mklml: third-party/mklml/src/extern_mklml-stamp/extern_mklml-mkdir
extern_mklml: third-party/mklml/src/extern_mklml-stamp/extern_mklml-download
extern_mklml: third-party/mklml/src/extern_mklml-stamp/extern_mklml-update
extern_mklml: third-party/mklml/src/extern_mklml-stamp/extern_mklml-patch
extern_mklml: third-party/mklml/src/extern_mklml-stamp/extern_mklml-configure
extern_mklml: third-party/mklml/src/extern_mklml-stamp/extern_mklml-build
extern_mklml: CMakeFiles/extern_mklml.dir/build.make
.PHONY : extern_mklml

# Rule to build all files generated by this target.
CMakeFiles/extern_mklml.dir/build: extern_mklml
.PHONY : CMakeFiles/extern_mklml.dir/build

CMakeFiles/extern_mklml.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/extern_mklml.dir/cmake_clean.cmake
.PHONY : CMakeFiles/extern_mklml.dir/clean

CMakeFiles/extern_mklml.dir/depend:
	cd /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2 /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2 /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build /home/qa_work/CI/workspace/sys_anakin_merge_build/anakin2/build/CMakeFiles/extern_mklml.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/extern_mklml.dir/depend

